#!/usr/bin/env python3
"""Build the Hill Country getaway page from curated data -> index.html"""
import json, re, sys, pathlib

HERE = pathlib.Path(__file__).parent
OUT = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parent / "index.html"

A_SA, A_NB, A_ATX, A_MF, A_FBG, A_FRIO = (
    "Near SA", "New Braunfels / Wimberley", "Austin / Lake Travis",
    "Marble Falls / Lakes", "Fredericksburg / Blanco", "Frio River")
AREAS = [A_SA, A_NB, A_ATX, A_MF, A_FBG, A_FRIO]

G, H, HO, AB, SP = "Glamping / cabins", "Hotel / inn", "Whole house", "Cabins", "State park cabin"

def P(id, name, town, area, kind, url, sa, atx, lo, hi, scen, gma, what, park, steps, bath, sleeps,
      price_note="", warn="", group="", has=(), flood="", reviews="", checked=False, conf="med",
      tier=None, climate="AC + heat", access=""):
    return dict(id=id, name=name, town=town, area=area, kindLabel=kind, url=url, driveSA=sa, driveATX=atx,
                priceLow=lo, priceHigh=hi, sceneryScore=scen, grandmaScore=gma, sceneryWhat=what,
                park=park, steps=steps, bath=bath, sleeps=sleeps, priceNote=price_note, warn=warn,
                groupNote=group, highlights=list(has), floodNote=flood, reviews=reviews, checked=checked,
                confidence=conf, priceTierOverride=tier, climate=climate, accessDetail=access)

PLACES = [
 # ---------------- Near SA ----------------
 P("tapatio", "Tapatio Springs Resort (ADA King room)", "Boerne", A_SA, H, "https://www.tapatiosprings.com/", 45, 105, 146, 268, 6, 9,
   "A private patio over a golf-course valley with limestone bluffs, rolling hills and big oaks. Pretty resort grounds, not wild country.",
   "Lots right next to the lodging buildings, with ADA spaces", "None. 4 first-floor ADA King rooms with stair-free entry",
   "Private. Grab bars + shower bench; 2 of the 4 ADA rooms have a roll-in shower", "2-4 per room, book several",
   "Plus a $24/night resort fee and tax. Up to 20% off for 3-night stays. A 'Gather the Family' package adds a $75 daily dining credit.",
   "Only 4 ADA rooms and only 2 with roll-in showers. Book early and get the roll-in room in writing.",
   "Grandma in an ADA King, everybody else in Double Queen rooms.", ("Pools", "Restaurant", "Live music on weekends"),
   "Not on a river.", "Few recent reviews online; official site updated 2026.", True, "med"),
 P("lacantera", "La Cantera Resort, Signia by Hilton (Hill Country View room)", "Far NW San Antonio", A_SA, H,
   "https://www.hilton.com/en/hotels/satcnsa-signia-la-cantera-resort-and-spa/", 25, 95, 409, 650, 6, 8,
   "Hilltop resort looking out over the golf course and wooded hills of NW San Antonio from your window or balcony.",
   "Accessible parking, elevators (big resort, so expect hallways)", "None", "Mobility rooms have roll-in showers (from about $409)",
   "Up to 4 per room", "Plus about 18% taxes and fees and a parking fee. Some dates jump way up ($879 seen for Oct 20).",
   "It's a big resort, so bring a wheelchair for the hallways.", "Everyone under one roof: 5 pools, spa, 6 restaurants.",
   ("5 pools", "Spa", "Restaurants on site"), "Hilltop, no flood risk.", "Google 4.5 from 4,700+ reviews.", False, "med"),
 P("casatopo", "Casa Topo at Sparrow Bend River Retreat", "Pipe Creek (Medina River)", A_SA, HO, "https://www.airbnb.com/rooms/52324171", 65, 140, 372, 620, 7, 7,
   "A big wrap-around porch looking over the lawn and trees to a private stretch of the spring-fed Medina River with limestone bluffs, about 100 yards off. Very dark, starry skies.",
   "Park right by the house", "None. A ramp goes up onto the porch, and it's one level inside",
   "2 baths, both tub/shower combos (bring a shower chair)", "12 (4 bedrooms)",
   "Whole house, Airbnb price with fees before tax: about $372-485/night weeknights, $483-620+ weekends.",
   "The house is up the bank, but it's still a river property. Watch the forecast.",
   "Rent the whole 8 acres if you want the campers and the second tiny house off the property.",
   ("Wrap-around porch", "Private river frontage", "Dark skies"), "House sits about 100 yards up from the river.",
   "Airbnb 4.96 from 148 reviews. Families rave about the river, stars and the host.", False, "high"),
 P("sunsetranch", "Sunset Ranch @ Medina Lake (3 houses)", "Mico, west side of Medina Lake", A_SA, HO, "https://sunsetflyinranch.com/", 55, 130, 565, 618, 7, 7,
   "The Ranch House's covered back patio looks over a big yard to Medina Lake and the dam. The Log House has 'views for miles' and sunsets. It's a working longhorn ranch.",
   "Drive up to each house (they're about 1/3 mile apart)", "Unknown. One level inside; you enter the Ranch House by a side door, ask about steps",
   "Private baths (5 across the 3 houses)", "Up to 22 (all 3 houses) or 12 (Ranch House only)",
   "About $565/night for all 3 houses with fees on fall dates checked. That's oddly less than the Ranch House alone ($618), so confirm.",
   "Medina Lake was only about 29% full in Sept 2026, so the lake view is low water right now.",
   "Book all 3 houses and you're the only guests on the ranch.", ("Longhorns", "Lake view", "Whole ranch to yourselves"),
   "Up on the ranch, not in a floodplain.", "Ranch House 4.98 from 51 reviews: 'breathtaking view of the lake'.", False, "med"),
 P("txhcr", "Texas Hill Country Resort (View Cabins)", "Medina (between Bandera and Kerrville)", A_SA, G,
   "https://www.txhillcountryresort.com/", 90, 140, 120, 285, 7, 7,
   "A hilltop resort where the View Cabins look out over the Hill Country from the back porch. Infinity pool with a hot tub, an observation deck and dark skies. Other cabins and RVs are around.",
   "Ask to park beside the cabin", "Unknown porch steps. The 1-King View Cabin is tagged Accessible",
   "Full private bath in every View Cabin", "View Cabin about 4; King Cabin up to 12",
   "View Cabins $120-140/night, King Cabin (sleeps 12) $285, before tax. Free cancel up to 7 days out; booking direct is cheapest.",
   "Reviews say there's no cell service and the road in from Kerrville is twisty. Make sure there's Wi-Fi or a landline for Grandma.",
   "Several View Cabins plus a King Cabin for the family. Skip the Bunk Houses (no bathroom).",
   ("Infinity pool + hot tub", "Pizza and beer on site", "Stargazing"), "Hilltop, not on a river.",
   "Only a handful of reviews (Campspot 3.0 from 2, Campendium 4.0 from 6).", False, "med"),
 P("luckydip", "The Lucky Dip (Medina River house)", "Pipe Creek (Medina River)", A_SA, HO, "https://www.airbnb.com/rooms/52114075", 65, 140, 236, 305, 7, 7,
   "Porch swings over a deer pasture out front. Out back, a park-like lawn and a huge pecan lead to the cypress-lined Medina River about 150 yards away, with sunsets over the hills.",
   "At the door, inside a gated 4 acres", "Front porch unknown; one level inside", "Every one of the 3 bedrooms has its own bathroom", "10",
   "Whole house with fees: about $236-305/night on fall dates checked. The cheapest whole house on this list.",
   "Almost no reviews from Jan 2025 to Sept 2026, and 2024 reviews flagged a weak fridge and floor. Ask what's been fixed.",
   "Room inside the gate if someone wants to bring an RV.", ("Own bath per bedroom", "River access", "Porch swings"),
   "House sits up above the river; the river bank itself is floodplain.", "Airbnb 4.88 from 112 reviews.", False, "med"),

 # ---------------- New Braunfels / Canyon Lake / Wimberley / Dripping Springs ----------------
 P("casitas", "Hill Country Casitas & Retreat", "Dripping Springs", A_NB, G, "https://www.hillcountrycasitas.com/lodging", 100, 55, 207, 549, 7, 9,
   "Little casitas on a Hill Country ridge over a hillside valley, with dark skies. The pavilion right next to the ADA casita has the easy big view (the best overlook is a hike).",
   "A parking spot right beside casitas #8 and #9", "La Benita (#9) is ADA; every casita except #1 is step-free",
   "Walk-in showers in all casitas", "2-8 per casita (11 casitas) + a Ranch House for 7",
   "About $207/night and up (Google, Sept 2026). The ADA casita was $319 weekdays / $399 weekends on their older rate sheet.",
   "No restaurant on site and the nearest HEB is about 15 miles, so bring groceries.",
   "Book several casitas side by side or the whole property for a reunion.", ("Pool + hot tub", "Pavilion + fire pit", "Dark skies"),
   "On a ridge, low flood risk.", "Google 5.0 from 214 reviews.", True, "med"),
 P("sunsetmill", "Inn at Sunset Mill Ranch (Granary Room)", "Wimberley", A_NB, H, "https://innatsunsetmillranch.com/", 70, 60, 202, 323, 8, 8,
   "A hilltop ranch on 25 acres. The Granary's deck (with its own hot tub and fire pit) looks over a valley with a spring-fed creek, cows and the sunset.",
   "Parking near all the suites (distance not given)", "Granary: ground level, no-curb walk-in shower, wider doors",
   "Private, walk-in shower", "Granary sleeps 2; whole property about 14",
   "Breakfast and parking included, no cleaning or resort fee. 2-night minimum on weekends.",
   "Kids 12+ only unless you rent the whole place. Most other rooms are upstairs, and the hilltop ground is uneven.",
   "Grandma in the Granary, family in the cabin and Carriage House, or rent the whole inn.", ("Private hot tub", "Breakfast", "Valley view"),
   "Hilltop. Coming from the south you cross the Blanco River; from Wimberley on RR 2325 you don't.", "", True, "med"),
 P("dreamgruene", "Dream Gruene (6BR riverfront, no stairs)", "New Braunfels (Gruene)", A_NB, HO, "https://www.airbnb.com/rooms/563210251410431554", 47, 60, 517, 948, 5, 10,
   "Two ground-floor condos on 2.5 acres of big trees and lawn by the Guadalupe at Gruene Rapids. The front door opens to a breezeway and parking lot; back patios look toward the river through the trees.",
   "Right at the front door (accessible spaces)", "Zero. No stairs, no curbs", "4 baths; both main bathrooms have low-curb walk-in showers", "16",
   "Whole place with fees before tax: about $517-750/night most fall and winter dates, up to about $950 on spring weekends.",
   "It's an in-town river condo, not a big Hill Country view. Only 4 parking spots.",
   "Two side-by-side condos: 6 bedrooms, 2 kitchens, 2 living rooms. Walk to Gruene Hall (uphill on the way back).",
   ("Easiest access on the list", "Walk to Gruene", "River access"), "Riverfront below Canyon Dam. Check the forecast.",
   "Airbnb 5.0 from 26 reviews.", True, "high"),
 P("fancylike", "\"Fancy Like at Canyon Lake\" estate", "Canyon Lake", A_NB, HO, "https://www.vrbo.com/2783992", 55, 80, 689, None, 5, 9,
   "5 private gated acres under huge live oaks, with deer, swings and a heated saltwater pool with a waterfall and a big hot tub. No lake view; the lake is 3 minutes away.",
   "At the door", "None ('no stairs required'), ramp on request", "5 baths", "20 (main house + casita)",
   "About $689/night average, all fees included (a 3-night quote was $2,066).",
   "No lake view. Bedroom #4 is curtained sleeping nooks, not a closed room.",
   "Built for big family trips; reviews mention a mom's 90th birthday.", ("Heated pool + hot tub", "Gated 5 acres", "Room for 20"),
   "Not on the water.", "VRBO 10/10 from 91 reviews.", False, "high"),
 P("canyonview", "Canyon Lake view house with an elevator", "Canyon Lake", A_NB, HO, "https://www.airbnb.com/rooms/1750099246989412463", 60, 80, 492, 1121, 8, 7,
   "High on a hillside with floor-to-ceiling windows and a top deck with chairs pointed straight at Canyon Lake and the sunset.",
   "Under 100 ft", "A few steps to the front door, then an ELEVATOR to all 3 floors", "4 king suites, each with its own bath", "18",
   "Whole house with fees: about $775/night weeknights and $1,120 weekends on sale dates checked (a longer stay averaged about $492).",
   "Brand-new listing with only 2 reviews (the host has 889 reviews at 4.87). Confirm the front-door step count.",
   "Game room and movie room for the kids.", ("Elevator", "Lake + sunset view", "Game + movie room"), "Hillside, well above the lake.",
   "2 reviews, both 5 stars.", False, "med"),
 P("summit", "Summit Vacation Resort (Accessible Tree Top Villa)", "New Braunfels (River Road)", A_NB, AB,
   "https://www.summitresorttexas.com/canyon-lake-vacation-rentals", 55, 65, 154, None, 6, 8,
   "A front porch looking over the Guadalupe River valley. The resort has river frontage, 3 pools and a hot tub. It's an RV resort, so there are neighbors.",
   "Not stated", "The accessible villa is single-story and wheelchair accessible", "Private", "10 (3 bedrooms); there are 3 of these villas",
   "From $154/night (weekends cost more). 25% off 5+ nights.",
   "Ask for the ACCESSIBLE Tree Top Villa by name; the regular ones are split-level with stairs. River Road was evacuated during the July 2025 flood.",
   "Book 2-3 accessible villas side by side for the whole family.", ("3 pools + hot tub", "River decks", "Cheap for a big group"),
   "On the Guadalupe below Canyon Dam.", "Campspot 4.5 from 29 reviews.", False, "med"),
 P("starlight", "Starlight Horizon (ramp cabins L, M, N)", "Canyon Lake", A_NB, AB, "https://starlighthorizon.com/", 55, 75, 190, None, 5, 8,
   "Modern cabins on 5 acres north of Canyon Lake with porches, a pool and big open sky for stargazing. No lake view, and the cabins sit close together.",
   "Not stated", "Cabins L, M and N have ramps; the others have steps", "2 baths per cabin", "8 per cabin (13 cabins)",
   "'As low as $190/night' per cabin. Fully refundable until 7 days out.",
   "The property is kept dark at night on purpose, so bring a lantern and put Grandma in cabin N by the pool.",
   "They sell 2-5 cabin groups for 11-40 people.", ("Pool", "Dark-sky stargazing", "Group cabin blocks"), "Upland, not on the river.", "", False, "med"),
 P("sagehill", "Sage Hill Inn & Spa", "Kyle (between Kyle and Wimberley)", A_NB, H, "https://www.sagehill.com/accommodations", 75, 35, 349, 1699, 6, 8,
   "88 quiet acres of oak ranch along Onion Creek with gardens, a pool, sunsets and stars. The Kyle King Room has a private deck facing north.",
   "Under 100 ft; the Ranch House has its own covered parking", "Kyle King Room is ground floor and barrier-free", "Private", "Rooms 2; Ranch House 7",
   "Weeknight rooms $349-509, weekend kings about $479, Ranch House $1,399-1,699.",
   "No kids under 16 unless you rent the whole inn. Strict cancellation.", "", ("Spa", "Pool", "Quiet"), "Along Onion Creek; ask which units sit above it.", "", False, "high"),
 P("cedars", "The Cedars Ranch (glamping domes + cabins)", "Wimberley", A_NB, G, "https://www.thecedarsranch.com/glamping/", 80, 60, 179, 405, 6, 7,
   "Real glamping: geodomes and cabins tucked into oaks and cedars on a 20-acre ranch. The dome's big curved window looks at the trees and night sky. Resort pool with daybeds.",
   "Not stated, ask", "2 accessible units exist but aren't named online, so call. The XL Dome has the king bed on the main floor",
   "Private, walk-in shower in the XL Dome", "Dome 4, Grand Cabin 6 (23 units)",
   "Weeknights average about $179, weekends about $347-405 (Kayak, taxes in).",
   "Most units have lofts, so Grandma takes a main-floor king. Weddings some weekends.",
   "Book a cluster of domes and cabins.", ("Geodomes", "Pool with daybeds", "Stargazing"), "Inland ranch.", "Kayak 8.8/10 from 10 ratings.", False, "med"),

 # ---------------- Austin / Lake Travis / Bastrop ----------------
 P("lakeway", "Lakeway Resort & Spa (accessible lake-view room)", "Lakeway (Lake Travis)", A_ATX, H, "https://www.lakewayresortandspa.com/stay", 100, 35, 196, 321, 8, 9,
   "All 9 accessible rooms are lake-view with a balcony over Lake Travis's deep water and the hills on the far shore.",
   "9 accessible spots closest to the entrance + covered drop-off; elevator", "None",
   "Roll-in shower in the accessible Double Queen and King lake-view rooms (confirm which)", "Up to 4 per room",
   "Plus a $50/night resort fee (includes a $25 food credit and a golf cart to the marina) and $10/night parking.",
   "Reviews call the rooms a little dated. It's a hotel, not glamping.", "Lots of rooms, so the whole family can be on one floor.",
   ("Lake-view balcony", "Swim-up bar", "Marina"), "Above Lake Travis.", "7.9/10 from 665 reviews; guests love the lake views.", True, "high"),
 P("laketravisescape", "Lake Travis Escape (lakefront house)", "Lago Vista (Lake Travis)", A_ATX, HO,
   "https://www.walkervr.com/vacation-rentals/rental/LakeTravisEscape643/", 110, 55, 423, 551, 8, 9,
   "A lakefront house on Lake Travis: the infinity pool, screened porch and deck all look out over the lake.",
   "6-car driveway, straight onto the main floor", "None from the driveway to the main floor (the pool level has steps)",
   "Main-floor bedroom with a walk-in shower; 4.5 baths total", "14",
   "Base rent about $423/night weeknights and $551 weekends; F1 weekend (Oct 23-25) about $1,093. Plus $425 cleaning, damage waiver, admin fee and tax. Book direct with Walker.",
   "Grandma stays on the main floor; the pool deck is down steps. Renter 25+, no parties.",
   "4 bedrooms including a bunk room for kids.", ("Infinity pool", "Screened porch", "Lake view from every room"),
   "Lake, not a river.", "VRBO 9.4 from 58 reviews.", True, "high"),
 P("bastropsp", "Bastrop State Park, accessible Cabins 12 + 14", "Bastrop", A_ATX, SP, "https://tpwd.texas.gov/state-parks/bastrop/fees-facilities/cabins", 95, 40, 130, 200, 5, 9,
   "Historic 1930s stone cabins in the Lost Pines forest with a big screened porch. Quiet woods, no lake or hill view.",
   "Wheelchair-friendly parking at Cabin 12", "Both labeled accessible (step count not published)", "Cabin 12: 2 baths; Cabin 14: 1 bath with a tub", "12 total (8 + 4)",
   "$200 (Cabin 12) + $130 (Cabin 14) per night, plus $5/adult/day park entry. 2-night weekends. Linens provided, bring pillows.",
   "Forest view only. Burn ban right now, so no campfires.", "Book both for 12 people.", ("Fireplace", "Screened porch", "Full kitchen"),
   "Upland forest.", "", False, "high"),
 P("cameron", "Cameron Ranch Glamping (lakefront cabins)", "Lake Bastrop", A_ATX, G,
   "https://cameronranchglamping.com/listing/premium-lakefront-cabin-2-the-magnolia-austin/", 100, 45, 299, 450, 7, 7,
   "A granite patio with a fire pit and grill right on the Lake Bastrop shoreline among pines and oaks. 'The lake was beautiful, right outside our cabin.'",
   "At the cabin", "Unknown, ask", "Private in each cabin (skip the safari tents, they use park restrooms)", "4 cabins side by side, 2-6 each",
   "Weekdays from about $299, weekends $349+.",
   "New operator (it used to be GLAT Austin), so recent reviews are thin, and the deposit is non-refundable. It's inside a public LCRA park.",
   "All 4 cabins sit together.", ("Lakefront patio", "Fire pit + grill"), "Off-river reservoir.", "", False, "med"),

 # ---------------- Marble Falls / Highland Lakes ----------------
 P("lakeviewretreat", "Lakeview Retreat (Lake Marble Falls house)", "Cottonwood Shores, Marble Falls", A_MF, HO, "https://www.airbnb.com/rooms/769862706617742662", 95, 65, 443, 547, 8, 8,
   "A back wall of windows and a patio facing a 180-degree view of calm Lake Marble Falls, with no houses across the water. Deer and geese in the yard, sunsets over the lake.",
   "2 covered carports + a disabled parking spot at the house", "Step-free into the house, one level", "Only 2 baths for up to 12 (big walk-in shower)", "12",
   "All-in with fees before tax: about $443-547/night on fall dates checked.",
   "Recent 3-star reviews about upkeep, stickers and ants. Steep hill down to the dock, so Grandma enjoys the view from the patio. Public boat ramp next door.",
   "3 bedrooms + bunks.", ("Kayaks", "Dock + gazebo", "Lake view from inside"), "Up the slope from the lake, just below Wirtz Dam.",
   "4.89 from 128 reviews.", True, "med"),
 P("lakeviewhaven", "Lakeview Haven (Lake LBJ house)", "Granite Shoals (Lake LBJ)", A_MF, HO, "https://www.airbnb.com/rooms/1450103417607645727", 105, 75, 545, 760, 7, 8,
   "Glass sliders open onto a covered patio and deck, then a long flat lawn runs right down to Lake LBJ.",
   "2 driveway spots", "One story, no stairs inside; front-door steps not confirmed", "The main bath has a separate walk-in shower", "6",
   "All-in about $545-760/night.", "Sleeps only 6. It's a busy boat lake (choppy water, goose droppings at the shore).",
   "Pair it with another rental for a bigger family.", ("Kayaks", "Flat lawn to the water"), "Lakefront on a constant-level lake.", "5.0 from 27 reviews.", True, "med"),
 P("chrissys", "Chrissy's Place (Lake Buchanan house)", "Tow (Lake Buchanan)", A_MF, HO, "https://www.airbnb.com/rooms/1360957303937113716", 135, 100, 337, 488, 8, 6,
   "Lake Buchanan's west shore. The living room and bedrooms face the lake, and you get sunrise over the water the second you walk in.",
   "Driveway for 3-4 cars at the door", "1 step to the front porch; one story", "Both baths are tub/shower combos (bring a shower chair)", "8",
   "All-in about $337-488/night (before tax).", "About 2h15m from SA. Stairs from the back deck down to the lake. The lake level goes up and down.",
   "", ("Lake view from inside", "Sunrise over the water"), "Shoreline of a lake that rises in floods.", "5.0 from 24 reviews, Guest Favorite.", True, "med"),
 P("antlers", "The Antlers Inn (Train Depot + cottages)", "Kingsland (Lake LBJ)", A_MF, H, "https://www.theantlers.com/rooms/train-depot.html", 105, 75, None, None, 6, 8,
   "A historic railroad resort on 8 wooded acres with gardens, cabooses and a vintage rail car. The Lake LBJ shoreline with a pier is a short stroll across the grounds.",
   "Park in front", "Train Depot: wrap-around deck with a ramp", "Depot: 2 full baths", "Depot 8; Sunrise + Sunset cottages 4 each",
   "Prices aren't online. Call 325-388-4411.", "The view from the door is the grounds, not the lake.",
   "Depot + both cottages = 16 people on one property.", ("Historic train cars", "Lake pier", "Gardens"), "", "", False, "med"),
 P("horseshoe", "Horseshoe Bay Resort", "Horseshoe Bay (Lake LBJ)", A_MF, H, "https://www.hsbresort.com/stay/", 100, 65, 158, 450, 7, 6,
   "A big lake-and-golf resort on Lake LBJ. Tower rooms can be booked with a lake or Hill Country view; waterfront condos look over the lake.",
   "Surface lots a walk away ($17/day), or valet drop-off at the entrance", "Accessible routes to rooms",
   "Accessible rooms have a tub with grab bars (no roll-in shower listed)", "Rooms 2-4; condos up to 8",
   "About $158-450/night plus a $45/night resort fee and parking.",
   "Parking isn't at the room and the accessible rooms have tubs. Confirm there's an accessible room with a lake view.",
   "Tons of rooms, villas and condos.", ("Beach", "Marina", "Restaurants"), "", "8.1/10 from 294 ratings.", True, "med", tier="$$"),
 P("buchananrv", "Lake Buchanan RV & Cabin Resort (waterfront cabins)", "Buchanan Dam", A_MF, AB, "https://lakebuchananrvresort.com/rates/", 115, 75, 121, 205, 7, 6,
   "A row of log cabins right on the Lake Buchanan shore with big sunsets over the water. It's an RV resort, so there are neighbors.",
   "Not stated", "Unknown. Call and ask for a waterfront cabin with no steps", "Private", "Waterfront row: 8 + 6 + 4 + 4 + 4...",
   "$121-205/night depending on cabin and season, +$10 on weekends.",
   "Few reviews and a new operator. The lake level goes up and down.", "The waterfront cabins sit side by side.",
   ("Lakefront", "Sunsets"), "", "Campendium 4.4 from 6: 'the sunsets were AMAZING'.", False, "med"),

 # ---------------- Fredericksburg / Johnson City / Blanco ----------------
 P("rockview", "Enchanted Rockview House", "Near Enchanted Rock (north of Fredericksburg)", A_FBG, HO, "https://www.airbnb.com/rooms/1121102044386443364", 120, 140, 321, 654, 8, 7,
   "The pink granite dome of Enchanted Rock right in view from the big front porch. Sunrise over the rock, deer, and very dark skies. This is the 'just sit and stare' one.",
   "Not stated", "One level; porch steps not stated", "2.5 baths", "10 (+ up to 12 more in sister cabins 0.1 mi away)",
   "About $321-346/night weeknights, $582-654 weekends (fees in).",
   "Rocky rural road with loose cattle, weak cell service, 30 min to groceries and a pharmacy.",
   "Sister cabins next door for overflow family.", ("Enchanted Rock view", "Dark skies", "Big porch"), "Upland, no river.",
   "4.92 from 51 reviews; the view gets praised in nearly every one.", False, "med"),
 P("outbound", "Outbound Ranch", "Near Hye (between Johnson City and Fredericksburg)", A_FBG, HO, "https://www.airbnb.com/rooms/1128390881661433941", 95, 80, 478, 1177, 8, 7,
   "A modern house alone on 33 acres with 10-foot floor-to-ceiling windows onto the Hill Country, porch sunrises, a private hot tub and a sauna.",
   "Under 100 ft", "Not stated, ask", "Private", "8",
   "About $478/night weeknights, $1,177 weekends (fees in).", "The splurge. Sleeps only 8. One-level layout not confirmed.",
   "", ("Hot tub", "Sauna", "Floor-to-ceiling windows"), "No river.", "4.96 from 45 reviews, Guest Favorite.", False, "med"),
 P("willowknoll", "Willow Knoll + Willow Knoll 2", "Willow City (16 mi NE of Fredericksburg)", A_FBG, HO, "https://www.airbnb.com/rooms/38096963", 110, 100, 237, 315, 6, 9,
   "Wooded 8.5 acres with a pond, deer and turkey every day, and very dark skies. Woods, not a long view. The famous Willow City Loop drive is 3 miles away.",
   "At the door", "Willow Knoll 2 is a first-floor apartment with wheelchair-width doors; the cabin is one level",
   "WK2: 2 baths; cabin: 1 bath with a tub", "About 11 + 8",
   "Airbnb with fees: about $237-315/night for Willow Knoll 2 (goes up with head count).",
   "Willow Knoll 2 sits under the hosts' home, so you may hear footsteps.", "Book both units side by side.",
   ("Pond", "Fire pit", "Stargazing"), "No river.", "4.99 (116 reviews) and 4.95 (108), Superhost.", False, "high"),
 P("baronscreek", "Barons CreekSide (Swiss cabins)", "Fredericksburg", A_FBG, G, "https://www.baronscreekside.com/", 85, 100, 269, 489, 6, 8,
   "Swiss log cabins with rocking-chair porches over spring-fed Barons Creek, a little waterfall, duck ponds and a vineyard, 2-3 minutes from Main Street.",
   "Not stated", "The Küssnacht cabin is ADA-approved", "Private", "Most cabins 2; Victorian 4; Big Lodge 9 (17 units)",
   "Weeknights $269-329 per cabin, Big Lodge $489. 3-night minimum most weekends.",
   "Only 1 ADA cabin and most sleep 2, so a family books several. It's creekside.", "Rent several cabins, or the whole 26 acres.",
   ("Creek + waterfall", "Near Main Street"), "Creekside, can flash-flood in heavy rain.", "", False, "high"),
 P("cartercreek", "Carter Creek Winery Resort (ADA villa)", "Johnson City", A_FBG, H, "https://www.cartercreek.com/", 75, 60, 155, 373, 5, 9,
   "Villas with private patios on a winery campus, with vineyard or pool views. The tasting room, brewery restaurant and spa are a short stroll.",
   "Not stated", "The ADA villa has a ramp; 46-inch paths", "Private", "2-4 per villa",
   "About $155 weeknights, $350 weekends, plus a $25/night resort fee.", "It's along US-290, not out in the wild.",
   "Book a row of villas.", ("Winery", "Spa", "Restaurant on site"), "Not on a river.", "Google 4.3 (277), Tripadvisor 4.6 (616).", False, "high"),
 P("rosehill", "Rose Hill Retreat (Primrose Cottage)", "Stonewall", A_FBG, H, "https://rose-hill.com/rooms/", 80, 75, 199, 399, 7, 7,
   "A hilltop country inn on 38 acres: rolling ranchland, longhorns and a vineyard next door. Primrose has a front deck with a 'fabulous view'.",
   "Not stated", "Primrose: wheelchair-accessible boardwalk ramp to the door", "Tub/shower combo (bring a shower chair)", "Primrose 2; Poppy House 3 bedrooms",
   "$199 Sun-Thu, $299 Fri-Sat per cottage, breakfast included; +$50 per extra guest. Poppy House $399.",
   "Kids 12+ only on Fri/Sat. Main House suites are upstairs.", "Grandma in Primrose, family in the West Cottage or Poppy House.",
   ("Breakfast", "Vineyard next door", "Longhorns"), "Hilltop.", "", False, "high"),
 P("johnsonhouse", "The Johnson House (inside Blanco State Park)", "Blanco", A_FBG, HO, "https://www.airbnb.com/rooms/49715151", 65, 70, 262, 373, 7, 6,
   "A 1911 farmhouse with a big porch, rockers and a swing looking at the Blanco River spilling over the dam, inside the state park. A shaded paved path goes to the town square in about 5 minutes.",
   "Not stated", "Porch steps (it's a raised old house), count unknown", "2 baths for up to 14", "14",
   "About $262/night weeknights, $373 weekends for 12 (fees in).",
   "Right on the Blanco River floodplain by the dam. Watch the forecast and leave on a Flood Watch.",
   "Blanco Riverside Getaway is next door for overflow.", ("River + dam view", "Porch swing", "Walk to town"), "Floodplain.",
   "4.80 from 163 reviews; a grandma with 5 grandkids loved it.", False, "med"),
 P("blancoriverside", "Blanco Riverside Getaway (cottages + villas)", "Blanco", A_FBG, AB, "https://www.blancoriversidegetaway.com/", 65, 70, 105, 175, 6, 7,
   "Cottages and villas backing onto Blanco State Park: big shade trees and a private gate into the park, with the river a short walk away.",
   "Not stated", "Villas One + Two are ground floor; Yellow Bungalow is one level; steps not stated", "Private (cottages have jetted tubs, ask for a shower)", "2-4 per unit, about 19 if you take all 8",
   "$105-175/night booking direct (Airbnb is $25-90 more).",
   "No ADA unit. A July 2026 review mentioned broken gates. The front faces US-281.", "Take the whole property.",
   ("Private gate into the state park",), "Near the Blanco River.", "4.94 (64) and 4.91 (44).", False, "high"),
 P("serengeti", "Sweet Serengeti Safari Ranch", "Blanco", A_FBG, G, "https://www.airbnb.com/rooms/32647476", 58, 58, 357, 381, 7, 6,
   "A 40-acre exotic animal ranch where zebras, wildebeest, oryx and an ostrich walk right up to the cabin to be hand-fed. Pond with a gazebo, dock and kayaks.",
   "At the door", "Steps at both cabin entrances; loft up a narrow stair", "Cabin: 1 bathroom for up to 8", "Cabin 8; 3 B&B rooms for 2 each",
   "Cabin about $357-381/night; B&B rooms about $210 with breakfast.",
   "Steps to get in and one bathroom. Books up fast.", "The kids will lose their minds.", ("Zebras at the window", "Pond + kayaks", "Hot tub"),
   "Not riverfront.", "4.99 from 540 reviews.", False, "med"),

 # ---------------- Frio River canyon ----------------
 P("riversedge", "River's Edge Cabin #3 at Oasis Resort", "Concan (Frio River)", A_FRIO, AB, "https://www.airbnb.com/rooms/1147335959647656156", 115, 200, 260, 430, 8, 8,
   "A big covered porch on a bluff right over the green Frio River, with cypress and live oaks below and Mt. Baldy in view.",
   "Driveway parking near the cabin", "About 0-1 step on a concrete walk; one level inside", "King suite has a walk-in stall shower with a seat",
   "8 (cabins 1-4 sit side by side, 8 each)",
   "Official rate $260-430/night plus cleaning. Fall is off-peak. 2-night minimum off-season.",
   "The river is down stairs. It's still riverfront, so leave on a Flood Watch. Spotty cell.",
   "Book cabins 1-4 together for up to 32 people.", ("River view porch", "Pool", "Riverbank"), "Raised bluff on the Frio.", "Airbnb 5.0 from 18 reviews.", True, "med"),
 P("garner", "Garner State Park cabins (ADA Cabin 18)", "Concan (Frio River)", A_FRIO, SP, "https://tpwd.texas.gov/state-parks/garner/fees-facilities/cabins", 115, 200, 130, 150, 6, 9,
   "Cabins under big oaks and pecans in Old Garner near the pavilion and a bend of the Frio, with limestone hills all around.",
   "Cabin 18 has a sidewalk from its own parking space", "Cabin 18: none, it's ADA", "Private bath with shower; central AC and heat", "4-6 per cabin, 17 cabins",
   "$130-150/night + $8/adult/day entry; 2-night minimum. Bring ALL bedding, towels and dishes.",
   "Only one ADA cabin, so book the day reservations open (up to 5 months ahead). Busy park; burn ban right now.",
   "Grab Cabin 18 plus the cabins around it.", ("Frio River", "Famous summer dances at the pavilion"), "Near the river.", "", True, "high"),
 P("riverview", "Camp Riverview ADA River-Facing Cabin", "Concan (Frio River)", A_FRIO, AB, "https://friocampriverview.com/cabin-rentals/", 110, 195, 149, 187, 6, 8,
   "An updated cabin with a railed deck under oaks in a family campground with half a mile of Frio River frontage. Trees and grass in front; the river is close.",
   "Not stated", "Listed as accessible", "Private", "6",
   "$149/night direct (Airbnb about $187 with fees).",
   "Busy campground (wristbands, quiet hours). Bring linens. Almost non-refundable. Floodplain.", "More river-facing cabins right nearby at $149.",
   ("Frio River frontage",), "Floodplain.", "5.0 from 4 reviews.", False, "high"),
 P("hiddenoaks", "Hidden Oaks at Concan", "Concan", A_FRIO, HO, "https://www.airbnb.com/rooms/1066979065036666945", 110, 195, 307, 317, 6, 8,
   "Tucked into live oaks; a big raised back deck looks over oak woods, a little creek and the canyon hills.",
   "Covered carport", "A railed ramp from the carport to the front door", "2 baths", "About 6",
   "About $307-317/night all-in before tax; 3-night minimum.",
   "The drive in crosses a messy neighbor's lot, AC struggled in summer reviews, and parts of the deck have no rails.",
   "", ("Ramp from carport", "Canyon view deck"), "Up a slope, not in the Frio floodplain.", "4.86 from 35 reviews.", False, "med"),
 P("chalet", "Mountain Top Chalet on 10 Acres", "Concan", A_FRIO, HO, "https://www.airbnb.com/rooms/556660408752545677", 117, 204, 568, 705, 8, 7,
   "A hilltop house on 10 acres with a wall of windows and a covered deck looking toward Garner State Park and the Frio valley. Deer, private pool.",
   "Not stated", "Unknown; reviews say the main floor is level enough for a walker", "5.5 baths, most bedrooms with their own", "16",
   "About $568-705/night plus about $420 cleaning.",
   "Runs on well water: low pressure reported, max 2 showers at once. Steep driveway.", "Big family setup; a Sept 2026 group was 12 adults + 5 grandkids.",
   ("Private pool", "Valley view", "Playground"), "Hilltop.", "4.89 from 140 reviews.", False, "med"),
 P("ringers", "Ringers Lodge (on the Frio)", "Concan", A_FRIO, HO, "https://www.airbnb.com/rooms/1374312303611165235", 115, 200, 1200, 1300, 7, 7,
   "A big shaded lawn and long covered porch with rockers right on the Frio, canyon hills across the valley, plus a pool, hot tub and outdoor bar.",
   "Paved parking by the house", "Looks like 1 low step to the porch", "6.5 baths", "16",
   "About $1,200-1,300/night all-in.", "Only 7 reviews. Riverfront. Pricey.", "A whole compound for the family.",
   ("Pool + hot tub", "Outdoor bar", "Riverfront"), "Riverfront.", "5.0 from 7 reviews; one family on their 5th year.", False, "med"),
 P("foxfire", "FoxFire Cabins", "Vanderpool (near Lost Maples)", A_FRIO, AB, "https://www.foxfirecabins.com/", 110, 180, 105, 160, 6, 6,
   "Log cabins on shady oak grounds with hills in view. The Sabinal River swimming hole with a limestone bluff is a short walk. Close to Lost Maples fall color.",
   "At the cabin", "Low stone porch, 1-2 steps", "1 bath with a tub", "6 per cabin (7 cabins) + Main House for 10",
   "Cabins $105-160/night, Main House $185-260.",
   "No cell service. Tubs, not walk-in showers. November books up for fall color. About an hour to a hospital.",
   "Take several cabins around the central pavilion.", ("River swimming hole", "Pavilion", "Family-run 40+ years"), "Borders the Sabinal River.",
   "4.94 from 155 reviews.", False, "med"),
 P("lostmaples", "Lost Maples Cabins", "Vanderpool", A_FRIO, AB, "https://lostmapleslodging.com/", 115, 180, 138, 158, 7, 6,
   "Cabins at the top of an RV park with views down the Sabinal Canyon, ridge sunrises, Milky Way skies and deer by the cabins.",
   "Not stated", "The Overlook has 3 porch steps; others not stated", "Tub/shower combos", "4 each (7 cabins)",
   "$138-158/night plus $25 cleaning.", "RV-park neighbors, weak cell, about 2 hours out. Peak fall weekends sell out.",
   "Several cabins side by side.", ("Canyon view", "Stargazing"), "Uphill from the river.", "4.95 from 43 reviews.", False, "med"),
]

SKIP = [
  ("Walden Retreats Hill Country", "Johnson City", "Gorgeous safari tents over the Pedernales cliffs, but all cars stay in a lot a 5-minute walk away on gravel, and the golf cart only runs at check-in and check-out.", "https://www.waldenretreats.com/"),
  ("Spoon Mountain Glamping", "Wimberley", "Has a truly wheelchair-accessible tent (Kingfisher), but it's adults only, 2 people per tent, and weekends run about $1,000/night.", "https://spoonmountainglamping.com/"),
  ("On The Rocks Glamping", "Marble Falls area", "One of the best valley views anywhere on this list, but no kids allowed, 2 per tent, and it's a rocky hilltop.", "https://glampingontherocks.com/"),
  ("Onera Wimberley", "Wimberley", "Pretty treetop and earth-home units, but most are up stairs and hills. Only 1 ADA unit and every unit sleeps 2.", "https://stayonera.com/locations/wimberley/"),
  ("Talula Mesa Glamping", "Lake Travis", "Glass-wall tents with private hot tubs over the lake, but the only bathroom is a shared bathhouse outside.", "https://www.talulamesa.com/accommodations"),
  ("Inks Lake State Park cabins", "Burnet", "Only $55/night, but no bathroom in the cabins. You walk to the park restrooms.", "https://tpwd.texas.gov/state-parks/inks-lake/fees-facilities/inks-lodging"),
  ("Camp Fimfo Texas Hill Country", "New Braunfels", "Fun water-park resort, but the big cabins have ONE bathroom for up to 12, nothing is marked accessible, and there's construction.", "https://campfimfo.com/texas-hill-country/ways-to-stay/cabins"),
  ("Postcard Cabins (the old Getaway)", "Wimberley", "Tiny cabins, and recent reviews say quality dropped after Marriott took over.", "https://www.marriott.com/en-us/hotels/aushc-postcard-cabins-hill-country-outdoor-collection-bonvoy/overview/"),
  ("Sittin' On Top of Texas", "Bandera", "Maybe the best porch view near SA, but it sleeps 2 and it's up a rocky gated road.", "https://www.airbnb.com/rooms/43715949"),
  ("Anything right on the Guadalupe in Kerr County", "Hunt, Ingram, Kerrville", "This stretch flooded in July 2025 and again in July 2026. Not worth it with Grandma.", ""),
]

ACTIVITIES = [
  (A_SA, "Old Tunnel bat flight", "short flat walk", "Millions of bats pour out of an old railroad tunnel at dusk. The upper viewing deck has ADA parking and a ramp.", "$2/person. Season ends Oct 31.", "https://tpwd.texas.gov/state-parks/old-tunnel/fees-facilities/accessibility"),
  (A_SA, "Hwy 16 river drive + Love Creek Orchards", "stay in car", "Shady two-lane drive from Bandera to Medina along the Medina River, ending at an apple bakery and patio cafe.", "Apples through October.", "https://www.lovecreekorchards.com/"),
  (A_SA, "Boerne Main Street + River Road Park", "short flat walk", "80+ shops and cafes with benches and restrooms; the park next to it sits on Cibolo Creek.", "Free.", "https://www.backroadstexas.net/boerne-hill-country-mile/"),
  (A_SA, "Haby's Alsatian Bakery", "few steps", "Classic bakery in Castroville since 1974. Easy stop heading west.", "Closed Sundays.", "https://www.habysbakery.com/"),
  (A_NB, "Santa's Ranch drive-thru lights", "stay in car", "A mile-plus drive through about 3 million lights. Everyone stays in the car, with hot chocolate and restrooms on site.", "Nov 6, 2026 to Jan 3, 2027. $37/car.", "https://santasranch.com/"),
  (A_NB, "Gruene Hall free daytime music", "short flat walk", "Texas's oldest dance hall with free live music on weekend afternoons. Old building, so call about access.", "Free daytime shows.", "https://gruenehall.com/calendar/"),
  (A_NB, "Devil's Backbone drive", "stay in car", "Ridge road between Wimberley and Blanco with a pull-out overlook across the valley. Twisty if she gets carsick.", "Free. Late afternoon light.", "https://www.backroadstexas.net/a-guide-to-the-devils-backbone-road/"),
  (A_NB, "The Salt Lick BBQ", "short flat walk", "Famous open-pit BBQ under the oaks in Driftwood. Accessible entrance, restrooms and seating reported.", "", "https://www.saltlickbbq.com/driftwood"),
  (A_NB, "Glass-bottom boats, San Marcos", "few steps", "30-minute ride over the crystal-clear springs. Two steps to board and no wheelchairs on the boat.", "$11 seniors.", "https://www.meadowscenter.txst.edu/education/glass-bottomboats.html"),
  (A_ATX, "Sunset at The Oasis on Lake Travis", "few steps", "Huge cliffside restaurant 450 ft over the lake with elevators to all decks. No reservations, so get there an hour before sunset.", "", "https://www.oasis-austin.com/faqs/"),
  (A_ATX, "Hill Country Flyer train", "few steps", "Vintage train from Cedar Park to Burnet's square and back, with a wheelchair lift to the car door.", "Saturdays.", "https://www.austinsteamtrain.org/special-events/hill-country-flyer/"),
  (A_ATX, "Lady Bird Johnson Wildflower Center", "short flat walk", "Calm gardens with free loaner wheelchairs and accessible main trails.", "$12 seniors weekdays.", "https://www.wildflower.org/visit"),
  (A_ATX, "Congress Avenue bats", "short flat walk", "Free sunset bat flight from the grassy area by the bridge.", "Through October.", "https://www.austintexas.org/things-to-do/outdoors/bat-watching/"),
  (A_MF, "Lookout Mountain overlook", "stay in car", "Drive right up to a 1,585 ft overlook over Lake LBJ. Best at sunset.", "Free.", "https://101highlandlakes.com/top-5-scenic-overlooks/"),
  (A_MF, "Blue Bonnet Cafe pie", "few steps", "Classic cafe since 1929. Pie happy hour weekdays 3-5pm. No reservations, the whole party has to be there.", "", "https://www.bluebonnetcafe.net/"),
  (A_MF, "Vanishing Texas River Cruise", "some walking", "2-hour cruise up the Colorado to Fall Creek Falls; bald eagle cruises Nov-Feb. Climate-controlled lower deck with restrooms, but the path down to the boat is steep, so call first.", "Eagle season Nov to Feb.", "https://www.vtrc.com/cruises"),
  (A_MF, "Walkway of Lights", "some walking", "About 2 million lights along the lake in downtown Marble Falls.", "Late Nov through Dec 31 (2026 dates TBA).", "https://visitmarblefalls.org/plan/itineraries/walkway-of-lights/"),
  (A_FBG, "LBJ Ranch driving tour", "stay in car", "Free 6-mile self-guided drive through LBJ's ranch along the Pedernales. Grab the permit at the Stonewall visitor center.", "Free. 9am-4:30pm.", "https://www.nps.gov/lyjo/planyourvisit/conditions.htm"),
  (A_FBG, "Wildseed Farms", "short flat walk", "200-acre wildflower farm with wide accessible paths, benches, a biergarten and a wine tasting room.", "Free entry.", "https://wildseedfarms.com/"),
  (A_FBG, "Luckenbach", "short flat walk", "The tiny song-famous town with free live music under the oaks. Bring a chair with a back.", "Free.", "https://www.visitfredericksburgtx.com/directory/luckenbach-texas-live-music/"),
  (A_FBG, "Pacific War Museum + Main Street", "some walking", "Big WWII museum right on Main with free loaner wheelchairs.", "Closed Tuesdays.", "https://www.pacificwarmuseum.org/accessibility"),
  (A_FBG, "Willow City Loop", "stay in car", "The most famous bluebonnet drive in Texas. Stay on the road, it's private ranch land.", "Late March to mid-April.", ""),
  (A_FRIO, "Twisted Sisters drive (one leg)", "stay in car", "The most dramatic scenery you can see from a car around here. Do one leg (like Vanderpool to Leakey), it's curvy.", "Daylight only.", "https://www.backroadstexas.net/twisted-sisters/"),
  (A_FRIO, "Garner State Park day visit", "short flat walk", "Cypress-lined Frio with the dam and old dance pavilion.", "$8/person.", "https://tpwd.texas.gov/state-parks/garner/alert"),
  (A_FRIO, "Lost Maples Cafe pie, Utopia", "few steps", "Small-town cafe since 1986 known for homemade pies. Call for hours.", "", "https://www.yelp.com/biz/lost-maples-cafe-utopia"),
]

TIPS = [
  {"heading": "When to go", "points": [
    "Best: late October through mid-December, then mid-March through April. Skip June to mid-September (heat and summer floods).",
    "November is the sweet spot: mild days, fall color at Lost Maples mid-month. It gets dark around 6pm after Nov 1.",
    "Out west (Kerrville, Fredericksburg, Leakey, Bandera) the first freeze usually hits early November, so make sure the unit has HEAT as well as AC.",
    "April is the prettiest: bluebonnets peak the first two weeks, and Marble Falls / Burnet / Fredericksburg book up early.",
    "Go Sunday to Thursday if you can. It's cheaper and many places need 2 nights on weekends."]},
  {"heading": "Dates that cost more or sell out", "points": [
    "Oct 2-4: Fredericksburg Oktoberfest + ACL weekend 1 (Austin)",
    "Oct 9-11: ACL weekend 2 (Austin)",
    "Oct 22-25: F1 in Austin + Fredericksburg Food & Wine Fest",
    "Nov 6-15: Wurstfest (New Braunfels / Gruene)",
    "Nov 26-29 (Thanksgiving) and Dec 19 to Jan 3",
    "Mid-March spring break, SXSW Mar 15-21 2027 (Austin), April bluebonnet weekends, Fiesta Apr 15-25 2027 (SA)"]},
  {"heading": "Flood safety (this one matters)", "points": [
    "The Hill Country is flash-flood country. The Guadalupe flooded deadly on July 4, 2025, and parts of Kerr, Kendall and Uvalde counties flooded again July 16-17, 2026.",
    "Pick a place up the hill WITH a river view over one that's right on the water.",
    {"html": "Check the address on the <a href=\"https://msc.fema.gov/portal/search\" target=\"_blank\" rel=\"noopener\">FEMA flood map</a> or <a href=\"https://map.texasflood.org\" target=\"_blank\" rel=\"noopener\">map.texasflood.org</a> before booking."},
    "Turn on Emergency Alerts on every phone. For Travis, Hays, Blanco, Burnet and Llano counties, sign up at WarnCentralTexas.org.",
    "If a Flood WATCH comes out, move Grandma to high ground right away. Don't wait for the warning; she can't move fast at 2am.",
    "Never drive through water over a road. When you get there, drive the way out once and note any low-water crossings."]},
  {"heading": "Fire pits and burn bans", "points": [
    "Right now (late Sept 2026) every county on this page has a burn ban, so no wood fires in fire pits.",
    "Propane grills are usually still OK. Ask the host if the fire pit runs on propane.",
    {"html": "Check the <a href=\"https://tfsweb.tamu.edu/\" target=\"_blank\" rel=\"noopener\">Texas A&amp;M Forest Service burn ban map</a> the week of the trip. Rain in the fall may lift the bans."}]},
  {"heading": "Ask the host before you book", "ordered": True, "points": [
    "How many feet from where we park to the door? Can we pull right up to drop her off?",
    "What's the path made of (pavement, deck, gravel, grass, stone steps)? Can you send a photo or video of it?",
    "How many steps to get in, and is there a handrail?",
    "Is the bathroom inside the unit? Is it a walk-in shower or a tub? Grab bars?",
    "How tall is the bed? Is it a normal bed on the main floor (not a loft, bunk or futon)?",
    "Is there lighting from the bed to the bathroom at night?",
    "What cools and heats the unit, and how well does it hold up on a 95-degree day or a freezing night?",
    "Which cell carriers work there? Is there Wi-Fi for calling? What's the exact address for 911?",
    "Is it in a floodplain? Did it flood in 2025 or 2026? Will you move us or refund us if there's a Flood Watch?",
    "Can you put our group side by side, with Grandma's unit closest to parking?",
    "Any weddings or events on the property that weekend?",
    "What's the cancellation policy if she gets sick?"]},
  {"heading": "Pack for Grandma", "points": [
    "All her meds + 3 extra days, a written med list, and her insurance cards",
    "Her disabled parking placard",
    "A rollator with big wheels or a folding transport wheelchair (gravel eats small wheels)",
    "A sturdy folding chair with arms and a back, not a low camp chair",
    "Shower stool and a non-slip mat, plus a toilet seat riser",
    "Motion nightlights for the path to the bathroom, and a headlamp for whoever walks with her",
    "Closed shoes with grip (no flip-flops on rock or caliche)",
    "Layers: hat and light clothes for heat, jacket and electric blanket for cold nights",
    "Water bottle and electrolyte packets (older folks don't feel thirsty, give water on a schedule)",
    "Allergy meds (cedar fever runs mid-Nov to Feb)",
    "Bug spray, and shake out shoes (scorpions and fire ants)",
    "A printed card with the rental address, nearest ER and family phone numbers"]},
  {"heading": "Nearest ER by area", "points": [
    "Near SA: Methodist ER Boerne (24/7); Peterson Regional in Kerrville for Bandera / Medina",
    "New Braunfels / Wimberley: CHRISTUS Santa Rosa New Braunfels; CHRISTUS Santa Rosa San Marcos is nearest to Wimberley",
    "Austin / Lake Travis: Baylor Scott & White Lakeway (24/7 ER)",
    "Marble Falls / Lakes: Baylor Scott & White Marble Falls (24/7 ER); Ascension Seton Highland Lakes in Burnet",
    "Fredericksburg / Blanco: Methodist Hospital Hill Country in Fredericksburg (Johnson City has no ER)",
    "Frio River: Uvalde Memorial Hospital; Peterson in Kerrville from the Leakey / Vanderpool side. Time the drive from your exact address."]},
  {"heading": "Money stuff", "points": [
    "Compare the TOTAL (cleaning fee + taxes), not the nightly price. Texas lodging tax runs up to about 17%.",
    "Book direct with the property when you can. It's often cheaper and easier to get the most accessible unit held for Grandma.",
    "Pick Flexible or Moderate cancellation, not the cheap non-refundable rate.",
    "One person books, everybody pays them back. Collect deposits BEFORE booking so nobody gets stuck.",
    "Consider trip insurance that covers a family member getting sick."]},
]

SCEN_T = [
  {"k": "S", "d": "Wow. Step out to a big view"},
  {"k": "A", "d": "Real view from the porch"},
  {"k": "B", "d": "Pretty grounds, trees, water nearby"},
  {"k": "C", "d": "Comfy, not much of a view"}]
PRICE_T = [
  {"k": "$", "d": "under $175"},
  {"k": "$$", "d": "$175 to $349"},
  {"k": "$$$", "d": "$350 to $599"},
  {"k": "$$$$", "d": "$600+"},
  {"k": "Call", "d": "price not online"}]
GMA_T = [
  {"k": "Easy", "d": "Park close, no steps or a ramp, private bath"},
  {"k": "OK", "d": "A step or a few, or a tub instead of a walk-in shower. Ask the host"}]

PICKS = [
  ("Best all-around for Grandma", "casitas", "Glamping feel without the hassle: step-free casitas, walk-in showers, parking right beside the ADA one, and a ridge view. Book several casitas and the whole family is together."),
  ("Easiest lake view (hotel)", "lakeway", "Every accessible room faces Lake Travis with a balcony and a roll-in shower. Park up front, elevator up, done."),
  ("Best whole-family lake house", "laketravisescape", "Sleeps 14, no steps from the driveway onto the main floor, and a main-floor bedroom with a walk-in shower. The whole back of the house is lake."),
  ("Best 'just sit and stare' view", "rockview", "Enchanted Rock right off the front porch, deer, and stars. One-level house for 10 with more cabins next door."),
  ("Best river cabin", "riversedge", "Porch on a bluff over the green Frio, basically no steps in, and 4 identical cabins side by side for the family."),
  ("Closest easy one (under an hour)", "dreamgruene", "47 minutes from SA. Zero steps, park at the door, room for 16, and you can walk to Gruene. Not a big view, but nothing is easier."),
  ("Best budget", "garner", "$130/night for the ADA cabin with its own sidewalk and bathroom, and more cabins around it for the family. Bring your own bedding."),
]

def tier_of(p):
    if p.get("priceTierOverride"): return p["priceTierOverride"]
    lo = p["priceLow"]
    if lo is None: return "Call"
    return "$" if lo < 175 else "$$" if lo < 350 else "$$$" if lo < 600 else "$$$$"

def scen_of(s): return "S" if s >= 8 else "A" if s == 7 else "B" if s == 6 else "C"
def gma_of(g): return "Easy" if g >= 8 else "OK"

for p in PLACES:
    p["priceTier"] = tier_of(p)
    p["scenery"] = scen_of(p["sceneryScore"])
    p["grandma"] = gma_of(p["grandmaScore"])
    p["match"] = p["sceneryScore"] + 1.15 * p["grandmaScore"] + (0.4 if p["checked"] else 0)
    p.pop("priceTierOverride", None)

data = {
  "meta": f"Checked September 24, 2026. {len(PLACES)} places passed the Grandma test out of 117 we looked at. Prices move, so confirm with the host.",
  "tiers": {"scenery": SCEN_T, "price": PRICE_T, "grandma": GMA_T},
  "areas": AREAS,
  "picks": [{"label": l, "id": i, "why": w} for l, i, w in PICKS],
  "places": PLACES,
  "skip": [{"name": n, "town": t, "why": w, "url": u} for n, t, w, u in SKIP],
  "activities": [{"area": a, "title": t, "walk": w, "what": x, "when": wh, "url": u, "access": ""} for a, t, w, x, wh, u in ACTIVITIES],
  "tips": TIPS,
  "footer": "Put together for the family, September 2026, from property websites, booking pages and guest reviews. Details change, so always confirm steps, bathroom and price with the host before you book.",
}

blob = json.dumps(data, ensure_ascii=False)
bad = [c for c in ("—", "–") if c in blob]
if bad: sys.exit(f"dash found: {bad}")
ids = {p["id"] for p in PLACES}
assert len(ids) == len(PLACES), "duplicate id"
for pk in PICKS: assert pk[1] in ids, pk
html = (HERE / "template.html").read_text().replace("__DATA__", blob.replace("</", "<\\/"))
OUT.write_text(html)
from collections import Counter
print(OUT, len(PLACES), "places")
print("price", Counter(p["priceTier"] for p in PLACES))
print("scen", Counter(p["scenery"] for p in PLACES))
print("gma", Counter(p["grandma"] for p in PLACES))
print("area", Counter(p["area"] for p in PLACES))
